### ISSUE TITLE
ImportError: cannot import name 'TypedDict' from 'typing'

### ISSUE THREAD

**Issue by cfz1998** [sebastian-gregoricchio/snakeATAC#1]
Hi Bro
Should I update python3.7 to python3.8?

![image](https://github.com/sebastian-gregoricchio/snakeATAC/assets/60096719/0aba16b4-8561-4219-9fa6-a93421f22ec9)

I appreciate your help!

**Comment by sebastian-gregoricchio** [comment]
Dear @cfz1998,
Thanks for rising the issue. I noticed indeed some issues in the conda environment of the pipeline. However, some co-dependencies issues raised and it took a while to fix it. I have now pulled a request to Bioconda in order to build a bioconda-recipe. I am waiting for the approval from the Bioconda-core. After that, it would be possible to install the environment in this way:

```
conda env create -n snakeATAC

conda activate snakeATAC

conda install -c bioconda -c conda-forge -c anaconda -c defaults snakeatac_env
```

I will keep you updated with this topic.

**Comment by sebastian-gregoricchio** [comment]
A bioconda recipe is now available on bioconda (https://anaconda.org/bioconda/snakeatac_env).

You should be able to create an environment by typing:
`conda create -n snakeATAC -c bioconda -c conda-forge -c defaults -c anaconda snakeatac_env`


It is also faster if you create an environment for mamba, another empty for snakeATAC and then install it with mamba:
```
conda create -n mamba conda-forge::mamba
conda create -n snakeATAC

conda activate mamba
mamba install -n snakeATAC -c bioconda -c conda-forge -c defaults -c anaconda snakeatac_env
```


I am closing now the issue, but let me know if something goes wrong. You can just open a new issue if necessary.
